# Generated by Django 4.1.1 on 2022-10-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=50)),
                ('priceDollars', models.PositiveIntegerField()),
                ('priceCents', models.PositiveSmallIntegerField()),
                ('shippingDollars', models.PositiveIntegerField()),
                ('shippingCents', models.PositiveSmallIntegerField()),
                ('stockCount', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('reported', models.BooleanField(blank=True, default=False)),
                ('isPending', models.BooleanField(blank=True, default=False)),
                ('isSold', models.BooleanField(blank=True, default=False)),
                ('canShip', models.BooleanField()),
                ('canMeet', models.BooleanField()),
                ('brand', models.CharField(default='', max_length=128)),
                ('image', models.FileField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=250)),
                ('isVisible', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sellerRating', models.FloatField(default=0)),
                ('sellerRatingCount', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop')),
            ],
        ),
    ]
