# Generated by Django 4.1.1 on 2022-09-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceDollars', models.PositiveIntegerField()),
                ('priceCents', models.PositiveSmallIntegerField()),
                ('shippingDollars', models.PositiveIntegerField()),
                ('shippingCents', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('reported', models.BooleanField()),
                ('isPending', models.BooleanField()),
                ('isSold', models.BooleanField()),
                ('canShip', models.BooleanField()),
                ('canMeet', models.BooleanField()),
            ],
        ),
    ]
