# Generated by Django 4.1.1 on 2022-11-01 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=250)),
                ('products', models.ManyToManyField(to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wishlist',
            field=models.ForeignKey(db_column='wishlist_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wishlist'),
        ),
    ]
