# Generated by Django 4.1.1 on 2022-11-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastViewed', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account')),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseTime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('totalPriceDollars', models.PositiveIntegerField()),
                ('totalPriceCents', models.PositiveSmallIntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='products/')),
                ('buyerEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pHistories', to='app.account')),
                ('sellerEmail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account')),
            ],
        ),
    ]
