# Generated by Django 4.1.1 on 2022-11-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productimage'),
        ('app', '0002_wishlist_account_wishlist'),
    ]

    operations = [
    ]
