# Generated by Django 4.1.1 on 2022-10-07 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('isVisible', models.BooleanField()),
                ('products', models.ManyToManyField(to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
    ]
