# Generated by Django 4.1.2 on 2022-10-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_listing_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stockCount',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='isPending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
