# Generated by Django 4.1.2 on 2022-10-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_stockcount_alter_product_ispending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isPending',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='isSold',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='reported',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
