# Generated by Django 4.1.1 on 2022-11-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_viewhistory_purchasehistory'),
        ('app', '0004_alter_productimage_image_shophistory'),
    ]

    operations = [
    ]
