# Generated by Django 4.1.1 on 2022-10-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shop_account_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sellerRating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sellerRatingCount',
            field=models.IntegerField(default=0),
        ),
    ]
