# Generated by Django 4.1.1 on 2022-10-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_sellerrating_account_sellerratingcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sellerRating',
            field=models.FloatField(default=0),
        ),
    ]
