# Generated by Django 4.1.1 on 2022-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_account_sellerrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='shop',
            name='isVisible',
            field=models.BooleanField(default=False),
        ),
    ]
