# Generated by Django 4.1.1 on 2022-11-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_image_alter_productimage_image'),
        ('app', '0006_shophistory_datetime_shophistory_quantity'),
    ]

    operations = [
    ]
