# Generated by Django 4.1.1 on 2022-11-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20221104_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='shophistory',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account'),
        ),
        migrations.AddField(
            model_name='shophistory',
            name='productId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shophistory',
            name='productName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shophistory',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shophistory',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
