# Generated by Django 4.1.1 on 2022-11-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shophistory_buyer_shophistory_productid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shophistory',
            name='buyerId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shophistory',
            name='buyerName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='shophistory',
            name='buyer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account'),
        ),
        migrations.AlterField(
            model_name='shophistory',
            name='profit',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
