# Generated by Django 4.1.1 on 2022-11-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shophistory_buyerid_shophistory_buyername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shophistory',
            name='buyerId',
        ),
    ]
