# Generated by Django 4.1.1 on 2022-11-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_shophistory_buyerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowOutOfStock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shophistory',
            name='numberSold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
