# Generated by Django 4.1.3 on 2022-12-06 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_shophistory_buyerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhistory',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
