# Generated by Django 4.1.1 on 2022-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_viewhistory_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowOutOfStock',
            field=models.BooleanField(default=False),
        ),
    ]
