# Generated by Django 4.1.1 on 2022-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_allowoutofstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
