# Generated by Django 4.1.1 on 2022-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_account_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
