# Generated by Django 4.1.3 on 2022-11-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_locations_alter_viewhistory_productid'),
        ('app', '0014_alter_account_verified'),
    ]

    operations = [
    ]
