# Generated by Django 4.1.3 on 2022-12-01 01:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='savedTags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
