# Generated by Django 4.1.1 on 2022-12-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_account_savedtags'),
        ('app', '0017_shophistory_locations'),
    ]

    operations = [
    ]
