# Generated by Django 4.1.1 on 2022-12-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_account_savedtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shophistory',
            name='product',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='shops/'),
        ),
    ]
