# Generated by Django 4.1.1 on 2022-12-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_shophistory_locations'),
        ('app', '0018_chatmessages'),
    ]

    operations = [
    ]
