# Generated by Django 4.1.1 on 2022-12-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20221208_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='venmoTag',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
