# Generated by Django 4.1.1 on 2022-12-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_shophistory_locations'),
        ('app', '0019_shophistory_locations_shophistory_product'),
    ]

    operations = [
    ]
