# Generated by Django 4.1.1 on 2022-12-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_chatmessages'),
        ('app', '0019_account_venmotag'),
    ]

    operations = [
    ]
