# Generated by Django 4.1.1 on 2022-12-09 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_0017_shophistory_locations_0018_chatmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNegotiating', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('shippingPriceDollars', models.PositiveIntegerField()),
                ('shippingPriceCents', models.PositiveIntegerField()),
                ('finalPriceDollars', models.PositiveIntegerField()),
                ('finalPriceCents', models.PositiveIntegerField()),
                ('isShipping', models.BooleanField(default=False)),
                ('trackingNumber', models.CharField(max_length=250)),
                ('trackingLink', models.CharField(max_length=500)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerEmail', to='app.account')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerEmail', to='app.account')),
            ],
        ),
    ]
