# Generated by Django 4.1.1 on 2022-12-08 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_merge_20221208_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='featuredProducts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
