# Generated by Django 4.1.1 on 2022-12-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_merge_0018_chatmessages_0019_account_venmotag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhistory',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
