# Generated by Django 4.1.1 on 2022-12-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_chatgroup_finalpricecents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='isNegotiating',
            field=models.BooleanField(default=True),
        ),
    ]
