# Generated by Django 4.1.1 on 2022-12-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_chatmessages_receiverimage_chatmessages_senderimage'),
        ('app', '0021_shop_featuredproducts'),
        ('app', '0022_alter_chatgroup_isnegotiating'),
    ]

    operations = [
    ]
