# Generated by Django 4.1.1 on 2022-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_merge_20221209_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
