# Generated by Django 4.1.1 on 2022-12-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_account_blockedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='shippingAddress',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
