# Generated by Django 4.1.1 on 2022-12-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_shop_description_alter_wishlist_description'),
        ('app', '0025_chatgroup_shippingaddress'),
    ]

    operations = [
    ]
