# Generated by Django 4.1.1 on 2022-12-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_merge_20221209_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='shippingAddress',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
